/**
 * Theme definitions. Each theme has an id, name, and colors map.
 * Colors are used across Track, Progress, and Settings.
 */
export const THEME_IDS = {
  DEFAULT: 'default',
  DARK: 'dark',
  YELLOWISH: 'yellowish',
  BLUEISH: 'blueish',
  GREENISH: 'greenish',
  PURPLE: 'purple',
};

export const THEMES = {
  [THEME_IDS.DEFAULT]: {
    id: THEME_IDS.DEFAULT,
    name: 'Default',
    statusBar: 'light',
    colors: {
      gradient: ['#FF6B9D', '#FF8E9B', '#FFB3A7'],
      headerText: '#FFFFFF',
      background: '#F5F5F5',
      surface: '#FFFFFF',
      text: '#333333',
      textSecondary: '#666666',
      textMuted: '#999999',
      primary: '#FF6B9D',
      primarySoft: '#FFF0F5',
      primaryAdd: '#FFF5F8',
      success: '#4CAF50',
      danger: '#FF5722',
      dangerSoft: '#FFF5F5',
      border: '#E0E0E0',
      borderLight: '#E8D5E0',
      tabBarActive: '#FF6B9D',
      tabBarInactive: '#999999',
      overlay: 'rgba(0,0,0,0.4)',
      chartUnder: '#A5D6A7',
      chartOver: '#FFB3D1',
      chartNone: '#E0E0E0',
      freeze: '#5C9EFF',
      trophy: '#FFD700',
      disabled: '#CCCCCC',
      placeholder: '#999999',
      shadow: '#000000',
    },
  },
  [THEME_IDS.DARK]: {
    id: THEME_IDS.DARK,
    name: 'Dark',
    statusBar: 'light',
    colors: {
      gradient: ['#6B2D5C', '#8B3D6C', '#AB5D7C'],
      headerText: '#FFFFFF',
      background: '#121212',
      surface: '#1E1E1E',
      text: '#E8E8E8',
      textSecondary: '#B0B0B0',
      textMuted: '#808080',
      primary: '#E91E8C',
      primarySoft: '#2D1B28',
      primaryAdd: '#2A1F25',
      success: '#4CAF50',
      danger: '#FF5722',
      dangerSoft: '#2D1F1F',
      border: '#333333',
      borderLight: '#3D3535',
      tabBarActive: '#E91E8C',
      tabBarInactive: '#808080',
      overlay: 'rgba(0,0,0,0.7)',
      chartUnder: '#2E5C2E',
      chartOver: '#5C2E3E',
      chartNone: '#333333',
      freeze: '#5C9EFF',
      trophy: '#FFD700',
      disabled: '#505050',
      placeholder: '#B8B8B8',
      shadow: '#000000',
    },
  },
  [THEME_IDS.YELLOWISH]: {
    id: THEME_IDS.YELLOWISH,
    name: 'Yellow',
    statusBar: 'dark',
    colors: {
      gradient: ['#FFF176', '#FFF9C4', '#FFFDE7'],
      headerText: '#5D4E00',
      background: '#FFFEF5',
      surface: '#FFFFFF',
      text: '#5D4E00',
      textSecondary: '#7D6B00',
      textMuted: '#9D8A00',
      primary: '#E6A800',
      primarySoft: '#FFF8E1',
      primaryAdd: '#FFFDE7',
      success: '#4CAF50',
      danger: '#D84315',
      dangerSoft: '#FFF0EB',
      border: '#FFF59D',
      borderLight: '#FFF9C4',
      tabBarActive: '#E6A800',
      tabBarInactive: '#9D8A00',
      overlay: 'rgba(0,0,0,0.4)',
      chartUnder: '#C5E1A5',
      chartOver: '#FFE0B2',
      chartNone: '#FFF59D',
      freeze: '#5C9EFF',
      trophy: '#FF8F00',
      disabled: '#E8E0B8',
      shadow: '#000000',
    },
  },
  [THEME_IDS.BLUEISH]: {
    id: THEME_IDS.BLUEISH,
    name: 'Blue',
    statusBar: 'light',
    colors: {
      gradient: ['#1976D2', '#42A5F5', '#64B5F6'],
      headerText: '#FFFFFF',
      background: '#E3F2FD',
      surface: '#FFFFFF',
      text: '#0D47A1',
      textSecondary: '#1565C0',
      textMuted: '#1976D2',
      primary: '#1565C0',
      primarySoft: '#E8F4FD',
      primaryAdd: '#E1F0FF',
      success: '#2E7D32',
      danger: '#C62828',
      dangerSoft: '#FFEBEE',
      border: '#BBDEFB',
      borderLight: '#B3E5FC',
      tabBarActive: '#1565C0',
      tabBarInactive: '#64B5F6',
      overlay: 'rgba(0,0,0,0.4)',
      chartUnder: '#81C784',
      chartOver: '#90CAF9',
      chartNone: '#BBDEFB',
      freeze: '#0D47A1',
      trophy: '#FFB300',
      disabled: '#90A4AE',
      shadow: '#000000',
    },
  },
  [THEME_IDS.GREENISH]: {
    id: THEME_IDS.GREENISH,
    name: 'Green',
    statusBar: 'light',
    colors: {
      gradient: ['#2E7D32', '#43A047', '#66BB6A'],
      headerText: '#FFFFFF',
      background: '#E8F5E9',
      surface: '#FFFFFF',
      text: '#1B5E20',
      textSecondary: '#2E7D32',
      textMuted: '#388E3C',
      primary: '#2E7D32',
      primarySoft: '#E8F5E9',
      primaryAdd: '#E0F2E1',
      success: '#1B5E20',
      danger: '#C62828',
      dangerSoft: '#FFEBEE',
      border: '#C8E6C9',
      borderLight: '#DCEDC8',
      tabBarActive: '#2E7D32',
      tabBarInactive: '#81C784',
      overlay: 'rgba(0,0,0,0.4)',
      chartUnder: '#A5D6A7',
      chartOver: '#C8E6C9',
      chartNone: '#C8E6C9',
      freeze: '#0277BD',
      trophy: '#FFA000',
      disabled: '#9E9E9E',
      shadow: '#000000',
    },
  },
  [THEME_IDS.PURPLE]: {
    id: THEME_IDS.PURPLE,
    name: 'Purple',
    statusBar: 'light',
    colors: {
      gradient: ['#7E57C2', '#9575CD', '#B39DDB'],
      headerText: '#FFFFFF',
      background: '#F5F5F5',
      surface: '#FFFFFF',
      text: '#333333',
      textSecondary: '#666666',
      textMuted: '#999999',
      primary: '#673AB7',
      primarySoft: '#EDE7F6',
      primaryAdd: '#F3E5F5',
      success: '#4CAF50',
      danger: '#FF5722',
      dangerSoft: '#FFF5F5',
      border: '#E0E0E0',
      borderLight: '#D1C4E9',
      tabBarActive: '#673AB7',
      tabBarInactive: '#9575CD',
      overlay: 'rgba(0,0,0,0.4)',
      chartUnder: '#A5D6A7',
      chartOver: '#FFB3D1',
      chartNone: '#E0E0E0',
      freeze: '#5C9EFF',
      trophy: '#FFD700',
      disabled: '#CCCCCC',
      shadow: '#000000',
    },
  },
};

export const getTheme = (id) => THEMES[id] || THEMES[THEME_IDS.DEFAULT];

/** Default colors used for backgrounds, cards, calendar, text – never change with theme. */
const DEFAULT_COLORS = THEMES[THEME_IDS.DEFAULT].colors;

/**
 * Effective colors: for non-Dark themes, backgrounds, cards, calendar (green/pink/gray), and
 * text stay default; only header, buttons, icons, and nav change. For Dark theme, use full
 * dark palette (dark backgrounds, cards, etc.) as before.
 */
export function getEffectiveColors(theme) {
  if (theme.id === THEME_IDS.DARK) return { ...theme.colors };
  const t = theme.colors;
  return {
    ...DEFAULT_COLORS,
    gradient: t.gradient,
    headerText: t.headerText,
    primary: t.primary,
    primarySoft: t.primarySoft,
    primaryAdd: t.primaryAdd,
    tabBarActive: t.tabBarActive,
    tabBarInactive: t.tabBarInactive,
  };
}

export const getThemeList = () => Object.values(THEMES);
